# Generated by Django 5.2.14 on 2026-05-15 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gussed_number', models.BigIntegerField()),
                ('win', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsersToPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_number', models.BigIntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.play')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.userstoplay'),
        ),
    ]
