# Generated by Django 5.2.14 on 2026-05-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='my_number',
            new_name='guess_number',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='gussed_number',
            new_name='my_number',
        ),
    ]
