# Generated by Django 5.2.14 on 2026-05-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_rename_my_number_guess_guess_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='user_id',
            new_name='user',
        ),
    ]
