# Generated by Django 5.2.14 on 2026-05-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_rename_user_id_play_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='hash',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
