# Generated by Django 5.2.14 on 2026-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_play_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess_number',
            field=models.CharField(max_length=4),
        ),
    ]
